// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lanlgyvmrhygdpcktzot.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxhbmxneXZtcmh5Z2RwY2t0em90Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1MjU3OTUsImV4cCI6MjA3MjEwMTc5NX0.gSoSOUOKXW0ZhgmF9Slt67IrF_8Ue7QSOfyY60yrR-o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});